name: Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  # Allows the EndBug/add-and-commit step to commit the package manager changes,
  # adding the AppMap language library and configuration file appmap.yml.
  # Once the EndBug/add-and-commit is removed, this permission can be removed, 
  # unless you need it for other reasons.
  contents: write

  # Allows the getappmap/archive-action to write a PR comment with the 
  # AppMap configuration status.
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    services:
        postgres:
          image: postgres:15
          env:
            POSTGRES_USER: misago
            POSTGRES_PASSWORD: misago
            POSTGRES_DB: misago
          ports:
            - 5432:5432

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      # Begin AppMap CI language agent installation
      # This snippet can be safely removed once the AppMap language agent has been
      # added to the project dependencies, and appmap.yml has been created.
      - name: Install AppMap tools
        id: install-appmap
        uses: getappmap/install-action@v1
        with:
          project-type: pip
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "ci: Add AppMap language agent and appmap.yml"
      # End AppMap CI language agent installation
      - name: Pytest
        env:
          DJANGO_SETTINGS_MODULE: devproject.test_settings
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          POSTGRES_DB: misago
          POSTGRES_USER: misago
          POSTGRES_PASSWORD: misago
          POSTGRES_HOST: localhost
        run: |
          pytest --cov=misago
      # Begin AppMap bootstrap archive step
      - name: Archive AppMaps
        id: appmap-bootstrap-archive-appmaps
        uses: getappmap/archive-action@v1
        with:
          revision: ${{ github.event.pull_request.base.sha }}
      # End AppMap bootstrap archive step
      - name: Linters
        run: |
          black --check .
          ruff misago/notifications misago/apiv2
      - name: Publish to coveralls.io
        uses: coverallsapp/github-action@v2